### ISSUE TITLE
watch: true throws warning

### ISSUE THREAD

**Issue by lifeiscontent** [graphile/graphile-engine#303] opened 2018-09-20 04:39 UTC
```
Failed to setup watch fixtures in Postgres database ️️⚠️
This is likely because your Postgres user is not a superuser. If the
fixtures already exist, the watch functionality may still work.
Enable DEBUG='graphile-build-pg' to see the error
```

seems like you're hardcoding a path here:

https://github.com/graphile/graphile-engine/blob/1e040ba6cef36cc166ac25e25c60d77e249bdd56/packages/graphile-build-pg/src/plugins/PgIntrospectionPlugin.js#L17

which is throwing here:

https://github.com/graphile/graphile-engine/blob/1e040ba6cef36cc166ac25e25c60d77e249bdd56/packages/graphile-build-pg/src/plugins/PgIntrospectionPlugin.js#L474-L484

**Comment by lifeiscontent** [comment] 2018-09-20 04:40
or wait, is this because in development you run a admin postgres URL?

**Comment by benjie** [comment] 2018-09-20 07:38
In order to set up the watch fixtures, PostGraphile needs to be given a superuser connection string. However once they are installed a regular connection string is fine, but you will get this warning because installing the latest version fails and we don’t have any versioning on it yet to check if it’s up to date.

Could you suggest modifications to the error message to make this clearer?

**Comment by lifeiscontent** [comment] 2018-09-20 09:58
@benjie I'd recommend making it a CLI command, and if there's something you can query in the DB do that on boot, and if a field isn't there, display the error and tell the user to run the command.

**Comment by benjie** [comment] 2018-09-20 15:35
Yeah; that's the long term plan, but my time's very constrained right now. Editing the error message doesn't take long by comparison and doesn't require testing.

**Comment by benjie** [comment] 2018-09-21 10:13
This is not a bug, and the error message seems fairly descriptive so I'm going to close this. Feel free to re-open with a better error message suggestion, or raise a PR to perform the watch schema detection.

**Closed by benjie** 2018-09-21 10:13 UTC
