### ISSUE TITLE
Extending schema with input which got suppressed by disableDefaultMutations does not work

### ISSUE THREAD

**Issue by pahlke** [graphile/graphile-engine#523] opened 2019-09-17 13:43 UTC
Hello,
I am using "disableDefaultMutations: true" in order to write the mutations by myself. When I then extend the schema with an input type with the same name as one which would have been generated automatically, I get at an error message that this type is already defined, although it is definitely not in the final schema. Is this intended? Or how can this be circumvented?

**Comment by benjie** [comment] 2019-09-17 17:20
The reason you're getting this is because we're creating the types ahead of time even though they're not used. This has turned out to be a bad practice, and we've tried to move away from it in many places but cannot do so for this in the V4 chain without it being a breaking change (I think).

Here's where the types are defined:

https://github.com/graphile/graphile-engine/blob/2335d6e9334680b927598ba9e748532323ad649d/packages/graphile-build-pg/src/plugins/PgTablesPlugin.js#L233-L304

Note these types are not only used for the default CRUD mutations, but also as inputs for the various PostgreSQL functions you can create, so we cannot simply disable them if `disableDefaultMutations` is set :disappointed: 

However, all is not lost. If you're certain that you don't need any of these types you can supply alternative inflectors for them using `makeAddInflectorsPlugin` so that the originals are named differently, freeing up their original names for you to use.

**Comment by ab-pm** [comment] 2019-09-18 10:02
A different, if not better, workaround than renaming the input types would be to `@omit create,update` the fields that you don't want in the input type, and use [`extend input … { … }`](https://github.com/graphql/graphql-js/issues/1095) in the schema extension to customise the rest. Maybe you don't have to customise it at all, you can just refer to the type in your `extendSchemaPlugin` and it will end up in the final schema *because you referenced it*.

**Comment by benjie** [comment] 2019-09-23 13:05
I'm closing this issue because it is not a bug, these type names should be reserved for function and mutation inputs.

**Closed by benjie** 2019-09-23 13:05 UTC
Labels: discussion, question
