### ISSUE TITLE
pgSettings not apart of `createPostGraphileSchema`

### ISSUE THREAD

**Issue by lifeiscontent** [graphile/graphile-engine#302] opened 2018-09-20 03:06 UTC
I'm trying to setup tests that check the authentication flow using `createPostGraphileSchema` and noticed I can't use `pgSettings` with it.

is this intentional? If so, how would you go about testing the GraphQL API?

before using postgraphile, I would just test a resolver and expect it to do the right things, but now since the resolvers are tied to the database, I'm not sure how to go about proper testing.

any help here would be appreciated. Thanks @benjie

**Comment by benjie** [comment] 2018-09-21 10:12
Yes, that's correct. The reason is that by the time you're in the schema the pgClient has been provisioned and the pgSettings have been applied. This is why `withPostGraphileContext` exists - it's responsible for getting a pgClient and applying the settings to it so that it can be passed to the GraphQL schema as the `context` for the query.

I've just spent some time writing this, but it's not tested at all:

https://www.graphile.org/postgraphile/testing-jest/

I'd really appreciate you trying it out and if there's any errors submitting a PR to fix them. In future I'm planning to make this much easier as part of solving this issue:

https://github.com/graphile/postgraphile/issues/777#issuecomment-421549445

I'm going to close this issue since it's not a bug, but feel free to keep discussing.

**Closed by benjie** 2018-09-21 10:12 UTC
