### ISSUE TITLE
Subscriptions and spikes of phantom transactions on PostgreSQL 

### ISSUE THREAD

**Issue by SlashKirill** [graphile/graphile-engine#726] opened 2021-03-26 07:02 UTC
### Summary

We heavily rely on Postgraphile Subscriptions mechanism for messages and RPC and noticed periodic spikes of transactions on PostgreSQL side. 

![unnamed](https://user-images.githubusercontent.com/45165554/112593505-9133aa00-8e42-11eb-8297-dab08def141d.jpg)

After investigation we found that those spikes are connected with keep-alive code in pg-pubsub: 

`      // Every 25 seconds, send 'select 1' to keep the connection alive

      client["keepAliveInterval"] = setInterval(() => {
        client.query("select 1").catch(e => {
          // eslint-disable-next-line no-console
          console.error(
            "Listen client keepalive error (will attempt reconnect):"
          );
          // eslint-disable-next-line no-console
          console.error(e);
          releaseClient(client);
          if (!pgPool.ending) {
            setupClient();
          }
        });
      }, 25000);`

So every 25 seconds the module executes "SELECT 1" for keep-alive purposes on the connection it uses to receive NOTIFY/LISTEN messages. As far as I understand this particular connection is used ONLY for NOTIFY/LISTEN communication, no other queries are sent across it. So, the execution of this query leads to spikes of transactions on PostgreSQL. If I disable that code completely - then those spikes go away, but at the moment when I say shutdown Postgraphile (and in breaks connections with PostgreSQL) I still get one single but large spike. Those spikes are in direct connection with the number of NOTIFY messages which are sent thru. Longer distance between "SELECT 1" executions (say I change it from 25sec to 60sec) - higher spikes are. So after the  study - the guess is that something is not working as it should be between node-postgres and PostgreSQL regarding confirmation or processing of NOTIFY messages received from DB. However, the messages are going thru (w/o delays) but it sounds like that some "ack" or some other minor processing to confirm received messages (or to do something else) is missing. And that "missed" processing is getting triggered when Postgraphile initiates "SELECT 1" query. 

### Steps to reproduce

Generation and consumption of continuous flow of messages over Postgraphile subscription. Every 25sec (upon keep-alive execution) "missed" processing is triggered which leads to transaction spike.

### Expected results

No spikes. 

### Actual results

High spikes of "phantom" transactions in DB initiated by "SELECT 1" SQL sent over connection used for NOTIFY/LISTEN stuff.

**Comment by benjie** [comment] 2021-03-29 09:52
I can reproduce this (independent of PostGraphile) with the following script:

```js
const { Pool } = require("pg");

const connectionString = "pubsub_tps";
const pool = new Pool({ connectionString });

async function main() {
  const client = await pool.connect();
  client.on("notification", n => {
    console.log(`${n.channel}: ${n.payload ?? "-no payload-"}`);
  });
  client.query("listen foo");
  console.log(`Listening on channel 'foo' on database '${connectionString}'`);
  setInterval(async () => {
    try {
      console.log("=== SELECT 1 ===");
      await client.query("select 1");
    } catch (e) {
      console.error(e);
      process.exit(2);
    }
  }, 30000);
}

main()
  .then(() => pool.end())
  .catch(e => {
    console.error(e);
    process.exit(1);
  });
```

Drop and recreate `pubsub_tps`, then run this script, then in another terminal, run `psql pubsub_tps` and execute:

```sql
select pg_notify('foo', now()::text); \watch 0.01
```

After 10 seconds kill the watch, and run:

```sql
select xact_commit + xact_rollback from pg_stat_database where datname = 'pubsub_tps'; \watch 1
```

You'll see the number settle, and then increment by one on each execution (as expected).

However when the next `=== SELECT 1 ===` runs, the output from `select xact_com...` from above jumps by a thousand or so in value.

I've not attempted to reproduce this with any other PostgreSQL clients (and reproducing it with psql would be unfair since the notifications aren't processed until you run the next statement); I suggest you escalate this to the `pg` module - @brianc might have some ideas.

It seems harmless so I'm going to go ahead and close this.

**Closed as completed by benjie** 2021-03-29 09:52 UTC
Labels: 🐛 bug
