### ISSUE TITLE
@graphile/lru is not declared as an explicit dependency

### ISSUE THREAD

**Issue by Macavirus** [graphile/graphile-engine#580] opened 2019-12-09 06:48 UTC
Using
```
    "graphile-build": "^4.5.0",
    "graphile-build-pg": "^4.5.0",
```
and one of them seems to not properly require `@graphile/lru`, likely similar to #245 .

Found this when using a module bundler (fuse-box) that throws when to tries to resolve the path:
`Error: Cannot find module '@graphile/lru'`.

Explicitly installing `@graphile/lru` fixes the issue, but likely not the proper fix.

**Comment by benjie** [comment] 2019-12-09 16:48
Both graphile-build (https://github.com/graphile/graphile-engine/blob/v4.5.0/packages/graphile-build/package.json#L33) and graphile-build-pg (https://github.com/graphile/graphile-engine/blob/v4.5.0/packages/graphile-build-pg/package.json#L40) correctly list `@graphile/lru` in their dependencies.

Please can you provide more reproduction steps?

**Comment by benjie** [comment] 2019-12-09 16:49
Closing this for now as I cannot reproduce it; please re-open with full reproduction steps.

**Closed by benjie** 2019-12-09 16:49 UTC
